theme: "minimal-mistakes-jekyll"
title: "Optimization Theory Lecture Notes"
author: "Peixuan Z"
description: "A collection of lecture notes on optimization theory."
url: "https://peixuanz.github.io/PZOptimizationTheory"
